# Generated by Django 2.1.2 on 2018-12-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=50)),
                ('niveau_etude', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
            ],
        ),
    ]
